# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      preview:
        docker:
          - image: circleci/ruby
        steps:
          - checkout
          - run:
              name: Set Feature Branch Name
              command: |
                echo "export SUBDOMAIN=`echo $CIRCLE_BRANCH | sed \"s/[^[:alnum:]]/-/g\"`" > $CIRCLE_BUILD_NUM
                echo "export CONTAINER=$CIRCLE_PROJECT_REPONAME-\$SUBDOMAIN" >> $CIRCLE_BUILD_NUM
                echo "export DIRECTORY=$CIRCLE_PROJECT_REPONAME/\$SUBDOMAIN" >> $CIRCLE_BUILD_NUM
          - run:
              name: Notify Preview Deploy Started
              command: |
                source $CIRCLE_BUILD_NUM
                curl -X POST -H "Content-Type: application/json" -H "Accept: application/vnd.github.ant-man-preview+json" \
                "https://api.github.com/repos/nebulab/awesomeprj/deployments?access_token=<token>" \
                -d '{ "ref": "'$CIRCLE_SHA1'", "auto_merge": false, "required_contexts": [], "environment": "preview", "transient_environment": true }' | \
                grep '"id"' | head -1 | awk '{gsub(/,/,""); print $2}' > github_deploy_id
          - run:
              name: Upload Application To Docker Server
              command: |
                source $CIRCLE_BUILD_NUM
                ssh ubuntu@qa.com "rm -fr $DIRECTORY && mkdir -p $DIRECTORY"
                tar c . | ssh ubuntu@qa.com "tar xC $DIRECTORY"
          - run:
              name: Run Docker Container On Docker Server
              command: |
                source $CIRCLE_BUILD_NUM
                ssh ubuntu@qa.com "\
                docker rm -f $CONTAINER; \
                docker run -d --restart always --name $CONTAINER \
                -e VIRTUAL_HOST=$SUBDOMAIN.qa.com \
                -e APP_HOSTNAME=$SUBDOMAIN.qa.com \
                $CONTAINER"
          - run:
              name: Notify Preview Deploy Complete
              command: |
                source $CIRCLE_BUILD_NUM
                curl -X POST -H "Content-Type: application/json" -H "Accept: application/vnd.github.ant-man-preview+json" \
                "https://api.github.com/repos/nebulab/awesomeprj/deployments/`cat github_deploy_id`/statuses?access_token=<token>" \
                -d '{ "state": "success", "environment_url": "http://'$SUBDOMAIN'.qa.com/", "environment": "preview"'